import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/pages/landing-page/navbar/navbar-component";
// import NavBar from "../components/pages/landing-page/navbar.component"
const poppins = Poppins({
  weight: ['400', '500','600','700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
});

const metadata: Metadata = {
  title: "Carsle",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
      <NavBar/>
        {children}
        </body>
    </html>
  );
}
